### ISSUE TITLE
New tensorflow version breaks pip installation

### ISSUE THREAD

**Issue by mlanas** [instadeepai/Mava#295]
# Problem
I installed the pip version of Mava in a virtual environment and I'm getting this error when running the debugging env example ([run_maddpg.py](https://github.com/instadeepai/Mava/blob/7e6fd836f429212e101585847c494ef793840db7/examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py)):

```bash
Traceback (most recent call last):
  File "examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py", line 26, in <module>
    from mava.systems.tf import maddpg
  File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/mava/systems/tf/maddpg/__init__.py", line 21, in <module>
    from mava.systems.tf.maddpg.system import MADDPG
  File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/mava/systems/tf/maddpg/system.py", line 24, in <module>
    import reverb
  File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/reverb/__init__.py", line 27, in <module>
    from reverb import item_selectors as selectors
  File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/reverb/item_selectors.py", line 19, in <module>
    from reverb import pybind
  File "/home/manuel/Mava/.venv/lib/python3.8/site-packages/reverb/pybind.py", line 1, in <module>
    import tensorflow as _tf; from .libpybind import *; del _tf
ImportError: /home/manuel/Mava/.venv/lib/python3.8/site-packages/reverb/libpybind.so: undefined symbol: _ZN4absl14lts_2020_09_2313hash_internal13CityHashState5kSeedE
```

# Execution

```bash
pip install --upgrade pip
pip install id-mava[reverb,tf,launchpad,envs,record_episode]
python examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py 
```

# Apparent fix
When doing this, the installed version of tensorflow is 2.6.0 **(which was released yesterday)** .
Installing the previous version with ```pip install tensorflow==2.5.0``` seems to solve the issue.

Not sure if this is a Mava problem, but I'll leave this here in case someone else encounters the same problem.

**Comment by KaleabTessera** [comment]
@mlanas Can you check your version of reverb (`pip show dm-reverb`). It is probably `0.3.1`. 

I think tensorflow 2.6 only works with reverb version `0.4.0`. We haven't adequately tested tf 2.6 and reverb 0.4.0 so that is why our `setup.py` points to tf 2.5 and dm-reverb 0.3.1. 

If you are planning on using tensorflow 2.6, please install dm-reverb 0.4.0. I have tested that it works, but we haven't thoroughly done performance/benchmarking on these new versions.

**Comment by mlanas** [comment]
@KaleabTessera  the reverb version was 0.3.1, but tf 2.6 was installed automatically, it out of the box did not work.

Now I retried the installation with a clean virtual environment and I'm getting ```dm-reverb==0.4.0``` and ```tensorflow===2.6.0```, but when I run the example I get this error:

```bash
Traceback (most recent call last):
  File "examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py", line 102, in <module>
    app.run(main)
  File "/home/manuel/new_mava_test/.venv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/manuel/new_mava_test/.venv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "examples/debugging/simple_spread/feedforward/decentralised/run_maddpg.py", line 88, in main
    local_resources = lp_utils.to_device(
AttributeError: module 'mava.utils.lp_utils' has no attribute 'to_device'

```

**Comment by KaleabTessera** [comment]
@mlanas Can you confirm you have pulled in the latest develop branch into your branch? We added this function to develop, so you shouldn't be receiving this error.

**Comment by KaleabTessera** [comment]
Closing for now, will re-open if issue still persists.
